---
production: &default
  serverPort: 5000
  baseUrl: http://www.urlcollector.com
  baseApi: /api
  tokenSecret: productiontoken
  mongodb: mongodb://localhost:27017/urlcollector
  languages:
    default: en
    list: [en, es, fr, pt, jp]

stage: &stage
  <<: *default
  baseUrl: http://stage.urlcollector.com

latest: &latest
  <<: *stage
  baseUrl: http://latest.urlcollector.com

development:
  <<: *latest
  baseUrl: http://localhost
  tokenSecret: developmenttoken
