---
production: &default
  serverPort: 5000
  baseUrl: http://www.urlcollector.com
  baseApi: /api/
  tokenSecret: productiontoken
  views:
    engine: ejs
    extension: .ejs
#    layout: main
  html:
    minify: true
    css:
      compress: true
      stylusPrecompile: true
  controllers:
    default: home
  languages:
    default: en
    list: [en, es, fr, pt, jp]

stage: &stage
  <<: *default
  baseUrl: http://stage.jhymer.com

latest: &latest
  <<: *stage
  baseUrl: http://latest.jhymer.com

development:
  <<: *latest
  baseUrl: http://localhost
  tokenSecret: developmenttoken
  html:
    minify: false
    css:
      compress: false
