---
production: &default
  baseApi: /api
  languages:
    default: en
    list: [en, es, fr, pt, jp]
  # Only in production:
  # process.env.TOKEN_SECRET -> generate token
  # process.env.MONGOLAB_URI -> mongo db

development: &development
  <<: *default
  serverPort: 5000
  tokenSecret: developmenttoken
  mongodb: mongodb://localhost:27017/urlcollector_dev

test:
  <<: *development
  tokenSecret: testtoken
  mongodb: mongodb://localhost:27017/urlcollector_test
